# Generated by Django 4.1 on 2022-08-20 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizzas', '0003_remove_topping_pizza_topping_pizza'),
    ]

    operations = [
        migrations.AddField(
            model_name='topping',
            name='field_name',
            field=models.ImageField(blank=True, upload_to=None),
        ),
    ]
