# Generated by Django 4.1 on 2022-08-20 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizzas', '0004_topping_field_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topping',
            name='field_name',
            field=models.ImageField(blank=True, upload_to='images/'),
        ),
    ]
