# Generated by Django 4.1 on 2022-09-06 17:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pizzas', '0007_pizza_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='pizza_comment',
            name='pizza',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='pizzas.pizza'),
            preserve_default=False,
        ),
    ]
